#!/bin/bash

echo "Install Homebrew manually."
echo "Install nvm manually."

install_homebrew_packages() {
	if [[ -x "$(command -v brew)" ]]; then
		echo "Installing Homebrew's packages ..."
		brew install neovim
		brew install tmux
		brew install ripgrep
		brew install shellcheck
		brew install jesseduffield/lazygit/lazygit
		brew install fd
		brew install lsd
		brew install lua
		brew install gnu-sed
		printf "Finished installing Homebrew's packages.\n\n"
	else
		echo "Homebrew is not installed or not executable."
	fi
}

install_homebrew_packages
