#!/bin/bash

install_homebrew_packages() {
	echo "Start installing Homebrew's packages ..."

	if [[ -x "$(command -v brew)" ]]; then
		echo "brew found. Installing packages ..."

		brew install neovim
		brew install tmux
		brew install ripgrep
		brew install shellcheck
		brew install jesseduffield/lazygit/lazygit
		brew install fd
		brew install lsd
		brew install lua
		brew install gnu-sed

		printf "Finished installing Homebrew's packages.\n\n"
	else
		echo "brew is not installed or not executable."
		exit 1
	fi
}

clone_neovim_config() {
	echo "Start cloning neovim config ..."

	if [[ ! -d ~/.config ]]; then
		mkdir ~/.config
	fi

	if [[ -x "$(command -v git)" ]]; then
		echo "git found. Cloning neovim config ..."

		git clone git@github.com:leehpham/lazyvim-config.git ~/.config/nvim

		printf "Finished cloning neovim config.\n\n"
	else
		echo "git is not installed or not executable."
		exit 1
	fi
}

clone_z() {
	echo "Start cloning z ..."

	if [[ -x "$(command -v git)" ]]; then
		echo "git found. Cloning z ..."

		git clone git@github.com:rupa/z.git ~/essential-scripts/z

		printf "Finished cloning z.\n\n"
	else
		echo "git is not installed or not executable."
		exit 1
	fi
}

clone_dotfiles() {
	echo "Start cloning dotfiles ..."

	if [[ -x "$(command -v git)" ]]; then
		echo "git found. Cloning dotfiles ..."

		git clone git@github.com:leehpham/dotfiles.git ~/dotfiles

		printf "Finished cloning dotfiles.\n\n"
	else
		echo "git is not installed or not executable."
		exit 1
	fi
}

main() {
	echo "Start setting things up ..."

	if [[ ! -x "$(command -v brew)" ]]; then
		echo "Please install Homebrew manually."
		exit 1
	fi

	if [[ ! -x "$(command -v nvm)" ]]; then
		echo "Please install nvm manually."
		exit 1
	fi

	install_homebrew_packages
	clone_neovim_config
	clone_z
	clone_dotfiles

	printf "Setup completed.\n\n"
}

main
