#!/bin/bash

ESSENTIAL_SCRIPTS_PATH="$HOME/essential-scripts"

pull_z() {
	echo "Start pulling z ..."

	local Z_DIR="z"
	local Z_PATH="$ESSENTIAL_SCRIPTS_PATH/$Z_DIR"

	if [[ -d "$Z_PATH" ]]; then
		echo "Pulling z ..."
		git -C "$Z_PATH" pull
		printf "z pulled.\n\n"
	else
		echo "$Z_PATH does not exist."
		exit 1
	fi

	printf "Finished pulling z.\n\n"
}

update_essential_scripts() {
	echo "Start updating essential scripts ..."

	if [[ -d "$ESSENTIAL_SCRIPTS_PATH" ]]; then
		pull_z
	else
		echo "$ESSENTIAL_SCRIPTS_PATH does not exist."
		exit 1
	fi

	printf "Finished updating essential scripts ..."
}

update_homebrew_packages() {
	echo "Start updating homebrew packages ..."

	if [[ -x "$(command -v brew)" ]]; then
		echo "Updating Homebrew's packages ..."

		brew update
		brew outdated
		brew upgrade

		printf "Homebrew's packages updated.\n\n"
	else
		echo "Homebrew is not installed or not executable."
		exit 1
	fi

	printf "Finished updating homebrew packages ..."
}

update_omz() {
	local OMZ_BASH_FILE="oh-my-zsh.sh"

	# $ZSH points to where OMZ is installed.

	if [[ -f "$ZSH/$OMZ_BASH_FILE" ]]; then
		echo "Updating OMZ ..."
		"$ZSH/tools/upgrade.sh"
		printf "Finished updating OMZ.\n\n"
	else
		echo "OMZ is not installed."
	fi
}

pull_powerlevel10k() {
	local POWERLEVEL10K_PATH="$ZSH/custom/themes/powerlevel10k"

	if [[ -d "$POWERLEVEL10K_PATH" ]]; then
		echo "Updating powerlevel10k ..."
		git -C "$POWERLEVEL10K_PATH" pull
		printf "Finished updating powerlevel10k.\n\n"
	else
		echo "$POWERLEVEL10K_PATH does not exist."
	fi
}

pull_zsh_plugin() {
	local PLUGIN_PATH="$ZSH/custom/plugins/$1"

	if [[ -d "$PLUGIN_PATH" ]]; then
		echo "Updating $1 ..."
		git -C "$PLUGIN_PATH" pull
		printf "Finished updating %s.\n\n" "$1"
	else
		echo "$PLUGIN_PATH does not exist."
	fi
}

update_omz_packages() {
	pull_powerlevel10k
	pull_zsh_plugin "zsh-autosuggestions"
	pull_zsh_plugin "zsh-syntax-highlighting"
}

update_tpm_packages() {
	if [[ -x "$(command -v tmux)" ]]; then
		echo "Updating TPM's packages ..."
		~/.tmux/plugins/tpm/bin/update_plugins all
		printf "Finished updating TPM's packages.\n\n"
	else
		echo "tmux is not installed or not executable."
	fi
}

main() {
	update_essential_scripts
	update_homebrew_packages
	update_omz
	update_omz_packages
	update_tpm_packages

}

main
